language: node_js
node_js:
  - "6"
script:
  - npm test
install:
  npm install -g firebase-tools
after_success:
  test $TRAVIS_NODE_VERSION = "6" && test $TRAVIS_BRANCH = "master" && firebase deploy --token $FIREBASE_TOKEN
